"""Add relationship between horoscopes and requests

Revision ID: 2578ed5607ed
Revises: 59a683060289
Create Date: 2025-02-05 14:42:22.046936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2578ed5607ed'
down_revision: Union[str, None] = '59a683060289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'horoscope_requests', 'horoscopes', ['horoscope_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'horoscope_requests', type_='foreignkey')
    # ### end Alembic commands ###
