"""Add zodiacs and compatibilities tables

Revision ID: 25df5a3a3534
Revises: c36c12312b11
Create Date: 2025-02-08 22:16:00.832556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25df5a3a3534'
down_revision: Union[str, None] = 'c36c12312b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
