"""Add unique constraint to horoscopes

Revision ID: 36f6eb1da74d
Revises: 62297580701b
Create Date: 2025-02-11 01:03:23.025613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f6eb1da74d'
down_revision: Union[str, None] = '62297580701b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_horoscope_sign_date_type', 'horoscopes', ['sign', 'date', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_horoscope_sign_date_type', 'horoscopes', type_='unique')
    # ### end Alembic commands ###
