"""Add horoscope_requests table

Revision ID: 59a683060289
Revises: 5ed4bcfeabab
Create Date: 2025-02-05 10:17:24.296495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a683060289'
down_revision: Union[str, None] = '5ed4bcfeabab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horoscope_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sign', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('horoscope_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horoscope_id'], ['horoscopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horoscope_requests_id'), 'horoscope_requests', ['id'], unique=False)
    op.create_index(op.f('ix_horoscope_requests_requested_at'), 'horoscope_requests', ['requested_at'], unique=False)
    op.create_index(op.f('ix_horoscope_requests_sign'), 'horoscope_requests', ['sign'], unique=False)
    op.create_index(op.f('ix_horoscope_requests_type'), 'horoscope_requests', ['type'], unique=False)
    op.drop_constraint('uq_horoscope_sign_type_date', 'horoscopes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_horoscope_sign_type_date', 'horoscopes', ['sign', 'type', 'date'])
    op.drop_index(op.f('ix_horoscope_requests_type'), table_name='horoscope_requests')
    op.drop_index(op.f('ix_horoscope_requests_sign'), table_name='horoscope_requests')
    op.drop_index(op.f('ix_horoscope_requests_requested_at'), table_name='horoscope_requests')
    op.drop_index(op.f('ix_horoscope_requests_id'), table_name='horoscope_requests')
    op.drop_table('horoscope_requests')
    # ### end Alembic commands ###
