"""Add tarot table

Revision ID: 81b9134479a6
Revises: d788c7232dfb
Create Date: 2025-02-17 18:57:27.258109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b9134479a6'
down_revision: Union[str, None] = 'd788c7232dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarot_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('arcana', sa.String(), nullable=False),
    sa.Column('suit', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('upright_meaning', sa.Text(), nullable=False),
    sa.Column('reversed_meaning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tarot_cards_id'), 'tarot_cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarot_cards_id'), table_name='tarot_cards')
    op.drop_table('tarot_cards')
    # ### end Alembic commands ###
