"""Add tarot table

Revision ID: 92219cb4c1cb
Revises: 36f6eb1da74d
Create Date: 2025-02-17 17:47:40.293042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92219cb4c1cb'
down_revision: Union[str, None] = '36f6eb1da74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
