"""Create horoscopes table

Revision ID: 9ddac570e860
Revises: 
Create Date: 2025-01-27 22:05:52.510123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ddac570e860'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horoscopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zodiac_sign', sa.String(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horoscopes_id'), 'horoscopes', ['id'], unique=False)
    op.create_index(op.f('ix_horoscopes_zodiac_sign'), 'horoscopes', ['zodiac_sign'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_horoscopes_zodiac_sign'), table_name='horoscopes')
    op.drop_index(op.f('ix_horoscopes_id'), table_name='horoscopes')
    op.drop_table('horoscopes')
    # ### end Alembic commands ###
