"""add_new_fields_to_horoscope

Revision ID: cdf277b057da
Revises: 9ddac570e860
Create Date: 2025-01-29 19:21:33.787274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf277b057da'
down_revision: Union[str, None] = '9ddac570e860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horoscopes', sa.Column('sign', sa.String(), nullable=True))
    op.add_column('horoscopes', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('horoscopes', sa.Column('type', sa.String(), nullable=True))
    op.add_column('horoscopes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('horoscopes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('horoscopes', sa.Column('language', sa.String(), nullable=True))
    op.add_column('horoscopes', sa.Column('source', sa.String(), nullable=True))
    op.add_column('horoscopes', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_horoscopes_zodiac_sign', table_name='horoscopes')
    op.create_index(op.f('ix_horoscopes_date'), 'horoscopes', ['date'], unique=False)
    op.create_index(op.f('ix_horoscopes_sign'), 'horoscopes', ['sign'], unique=False)
    op.create_index(op.f('ix_horoscopes_type'), 'horoscopes', ['type'], unique=False)
    op.drop_column('horoscopes', 'zodiac_sign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horoscopes', sa.Column('zodiac_sign', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_horoscopes_type'), table_name='horoscopes')
    op.drop_index(op.f('ix_horoscopes_sign'), table_name='horoscopes')
    op.drop_index(op.f('ix_horoscopes_date'), table_name='horoscopes')
    op.create_index('ix_horoscopes_zodiac_sign', 'horoscopes', ['zodiac_sign'], unique=True)
    op.drop_column('horoscopes', 'is_active')
    op.drop_column('horoscopes', 'source')
    op.drop_column('horoscopes', 'language')
    op.drop_column('horoscopes', 'updated_at')
    op.drop_column('horoscopes', 'created_at')
    op.drop_column('horoscopes', 'type')
    op.drop_column('horoscopes', 'date')
    op.drop_column('horoscopes', 'sign')
    # ### end Alembic commands ###
