"""Add created_at and updated_at fields

Revision ID: e5b8ade7edd6
Revises: 2578ed5607ed
Create Date: 2025-02-07 16:27:14.991630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b8ade7edd6'
down_revision: Union[str, None] = '2578ed5607ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horoscope_requests', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('horoscope_requests', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horoscope_requests', 'updated_at')
    op.drop_column('horoscope_requests', 'created_at')
    # ### end Alembic commands ###
