"""Add zodiacs and compatibilities tables

Revision ID: f968c15a28d3
Revises: 25df5a3a3534
Create Date: 2025-02-08 23:06:36.254007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f968c15a28d3'
down_revision: Union[str, None] = '25df5a3a3534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
